# Generated by Django 5.1.1 on 2024-09-29 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantAPI', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='Image',
            field=models.ImageField(default='menu/Default.png', upload_to='menu/'),
        ),
    ]
